name: deploy to lambda
on:
  push:
    branches:
      - main

jobs:

  deploy_lambda:
    name: build the lambda function zip file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: GithubActionsSession
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          

      - name: AWS ECR Auth
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 193172378049.dkr.ecr.us-east-2.amazonaws.com
          docker build -t fantasy-football-dashboard .
          docker tag  fantasy-football-dashboard:latest 193172378049.dkr.ecr.us-east-2.amazonaws.com/fantasy-football-dashboard:latest
          docker push 193172378049.dkr.ecr.us-east-2.amazonaws.com/fantasy-football-dashboard:latest
      - name: Update Lambda Environment Variables
        run: |
          aws lambda update-function-configuration \
            --function-name fantasy-football-dashboard \
            --timeout 120 \
            --role ${{ secrets.AWS_ROLE_TO_ASSUME }}
   
      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name fantasy-football-dashboard \
            --image-uri 193172378049.dkr.ecr.us-east-2.amazonaws.com/fantasy-football-dashboard:latest 
